# ============================================================================
#  Prince Alex TicketHub - single-file Worker build (for Dashboard deploys)
#  ---------------------------------------------------------------------------
#  The Cloudflare dashboard code editor deploys ONE module, named worker.js.
#  worker/index.js does `import { ... } from "./emails.js"`, so a dashboard
#  deploy of index.js alone fails at runtime with:
#      Uncaught Error: No such module "emails.js". imported from "worker.js"
#
#  This script inlines worker/emails.js into worker/index.js and writes
#  worker/worker.js - one self-contained ES module with the same behaviour.
#
#  Use it when you deploy by pasting into the dashboard. When you deploy with
#  `wrangler deploy` (multi-module) you do NOT need this: point wrangler at
#  index.js and it follows the relative import itself.
#
#  Usage:
#      powershell -ExecutionPolicy Bypass -File worker\build-single-file.ps1
#      powershell -ExecutionPolicy Bypass -File worker\build-single-file.ps1 -OutFile out.js
# ============================================================================
param([string]$OutFile)

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$emailsPath = Join-Path $here 'emails.js'
$indexPath = Join-Path $here 'index.js'
if(-not $OutFile){ $OutFile = Join-Path $here 'worker.js' }

function Read-Source([string]$path){
  if(-not (Test-Path $path)){ throw "Missing source file: $path" }
  $text = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
  return $text.TrimStart([char]0xFEFF)
}

$emails = Read-Source $emailsPath
$index = Read-Source $indexPath

# 1) emails.js becomes the body of a function: drop the `export ` keywords.
$body = [regex]::Replace($emails, '(?m)^export\s+', '')

# 2) Exactly the names index.js imports, so the swap is behaviour-preserving.
$api = @(
  'queueEmail','dispatchSoon','dispatchOutbox','requeueEmail','sendTemplateNow','sendTestEmail',
  'isEmailConfigured','isTemplate','templateList','templateCategory','outboxRowView','outboxStats',
  'emailStatus','loadEmailSettings','resetEmailSettingsCache','brandOf','base64Encode',
  'normalisePayloadLinks','mergeEmailLinks'
)

$wrapper = @()
$wrapper += '/* --- BEGIN inlined worker/emails.js (generated) --- */'
$wrapper += 'const EMAILS_MODULE = (function(){'
$wrapper += $body
$wrapper += ''
$wrapper += 'return { ' + ($api -join ', ') + ' };'
$wrapper += '})();'
$wrapper += 'const { ' + ($api -join ', ') + ' } = EMAILS_MODULE;'
$wrapper += '/* --- END inlined worker/emails.js --- */'
$wrapperText = $wrapper -join "`r`n"

# 3) Replace the relative import with the inlined module (no regex substitutions
#    on the replacement text: plain string surgery keeps $ characters intact).
$rx = New-Object System.Text.RegularExpressions.Regex('(?s)import\s*\{.*?\}\s*from\s*["'']\./emails\.js["'']\s*;')
$match = $rx.Match($index)
if(-not $match.Success){ throw 'Could not find the "./emails.js" import inside index.js.' }
$out = $index.Substring(0, $match.Index) + $wrapperText + $index.Substring($match.Index + $match.Length)

# 4) Generated header + write (UTF-8 without BOM).
$header = @"
/* ============================================================================
   Prince Alex TicketHub API - SINGLE FILE BUILD
   Generated $(Get-Date -Format 'yyyy-MM-dd HH:mm') from worker/index.js + worker/emails.js

   DO NOT EDIT THIS FILE. Change index.js or emails.js and re-run
   worker\build-single-file.ps1 (or worker\build-single-file.cmd).

   Why this file exists: the Cloudflare dashboard code editor deploys a single
   module (worker.js), where a relative import of ./emails.js fails with
   'No such module "emails.js"'. Everything is inlined here, so this file can be
   pasted or uploaded as-is and keeps working with the same bindings/secrets:
   DB (D1), BUCKET (R2), BREVO_API_KEY, FIREBASE_PROJECT_ID, ALLOWED_ORIGINS, ...
   =========================================================================== */
"@

[System.IO.File]::WriteAllText($OutFile, $header + "`r`n" + $out, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0}" -f $OutFile)
Write-Host ("  {0:N0} bytes, {1:N0} lines" -f (Get-Item $OutFile).Length, (Get-Content $OutFile).Count)
