# ============================================================================
#  Prince Alex TicketHub - build the PDF test harness
#  ---------------------------------------------------------------------------
#  tools/_pdfkit-test.html exercises pdfkit.js on its own.
#  tools/_pdfkit-agreement-test.html needs the REAL agreement-page code, so
#  this script slices it out of organizer-agreement/index.html and writes
#  tools/_pdfkit-agreement.js with the few stubs it depends on.
#
#  Slicing the shipped file (rather than keeping a copy of it) means the test
#  can never pass against stale code: regenerate, then run the page.
#
#  Usage:
#      powershell -ExecutionPolicy Bypass -File tools\build-pdfkit-harness.ps1
# ============================================================================
param()

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$page = Join-Path (Split-Path -Parent $root) 'organizer-agreement\index.html'
$outFile = Join-Path $root '_pdfkit-agreement.js'

if(-not (Test-Path $page)){ throw "Cannot find $page" }
$lines = [System.IO.File]::ReadAllLines($page)

function Find-Line([string]$pattern){
  for($i = 0; $i -lt $lines.Count; $i++){
    if($lines[$i] -match $pattern){ return $i }
  }
  throw "Marker not found in index.html: $pattern"
}

# The shared helpers the PDF block uses: KES, esc, and the Kenya-time formatters.
$helpStart = Find-Line 'const BRAND = \{ product:'
$helpEnd   = Find-Line 'function qs\(o\)\{'
# The PDF block: its banner comment down to the HTML download comment.
$pdfStart  = Find-Line 'signed PDF ===='
$pdfEnd    = Find-Line 'The signed document is behind'

if($helpEnd -le $helpStart){ throw 'Helper range looks wrong.' }
if($pdfEnd -le $pdfStart){ throw 'PDF range looks wrong.' }

$helpers = $lines[$helpStart..($helpEnd - 1)]
$pdf     = $lines[$pdfStart..($pdfEnd - 2)]

$head = @"
// GENERATED by tools\build-pdfkit-harness.ps1 - do not edit.
// Real code sliced out of organizer-agreement\index.html:
//   helpers  lines $($helpStart + 1)-$helpEnd
//   pdf block lines $($pdfStart + 1)-$($pdfEnd - 1)
// Regenerate after editing that page.
"@
$mid = @"

// --- stubs for the handful of page globals this block touches ---
function toast(){}
let AG = null;
"@
$tail = @"
window.__harness = {
  buildAgreementPdf: buildAgreementPdf,
  downloadPdf: downloadPdf,
  setAG: function (v){ AG = v; }
};
"@

$body = $head + ($helpers -join "`r`n") + $mid + ($pdf -join "`r`n") + $tail
[System.IO.File]::WriteAllText($outFile, $body, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0}" -f $outFile)
Write-Host ("  {0:N0} bytes" -f (Get-Item $outFile).Length)
